version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: facturapy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=facturapy
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
